/**
 * Signal HQ — Marketing hub data.
 *
 * 100 marketing approaches, every one cleared by the three-director panel
 * (Brand · Marketing · Feasibility) with no reservation. This is authored
 * canon, not an operator-edited runtime surface — it follows the
 * `one-pagers.ts` precedent (a closed, typed, enumerated list), not the
 * localStorage operator surfaces.
 *
 * The panel is the gate every approach below has already passed:
 *   BRAND       hard-fails any non-goal (paid ads, Product Hunt / Show HN,
 *               daily short-form treadmill, AI-listicle SEO at volume,
 *               mass-blast outbound, content-for-frequency) and any banned
 *               register. Applies the logo-swap test.
 *   MARKETING   fails anything that doesn't measurably move the venue
 *               engine against the M1–M6 sequence and the five success
 *               metrics. "Nice" is a fail.
 *   FEASIBILITY fails anything beyond solo founder + agent factory +
 *               ~3.5 deliberate hrs/week + €0 + 6 months. No sales-team
 *               output.
 *
 * Ranked within each bucket by leverage on the negative-CAC engine.
 * Source: docs/MARKETING_PLAN_6MO.md · the 2026.05 plan.
 */

export type Impact = "Engine" | "High" | "Medium";
export type Effort = "Low" | "Medium";

export type Approach = {
  /** Stable id: bucket-prefix + rank, e.g. "VE-01". */
  id: string;
  rank: number;
  title: string;
  /** What it actually is — one plain sentence. */
  what: string;
  /** The sentence a generic competitor would never publish — why it clears the panel. */
  edge: string;
  impact: Impact;
  effort: Effort;
  /** Where it lands in the M1–M6 sequence. */
  month: string;
};

export type BucketKey =
  | "venue-engine"
  | "sponsored-loop"
  | "search-comparison"
  | "proof-narrative"
  | "brand-moat"
  | "community-partnerships";

export type Bucket = {
  key: BucketKey;
  /** Lowercase nav label (HQ register). */
  label: string;
  /** One-line strategic role. */
  role: string;
  /** Why this bucket exists, in the plan's own terms. */
  rationale: string;
  approaches: Approach[];
};

const VENUE_ENGINE: Approach[] = [
  {
    id: "VE-01",
    rank: 1,
    title: "Venue-seeded micro-demo",
    what: "The first outreach email links a workspace pre-built with that venue's real wedding workflow.",
    edge: "A competitor sends a trial link; we send a finished workspace with their venue's name already in it.",
    impact: "Engine",
    effort: "Medium",
    month: "M1",
  },
  {
    id: "VE-02",
    rank: 2,
    title: "Founding 15 live scarcity lock",
    what: "One page: €1,500-for-life, a remaining-slots counter wired to real signings.",
    edge: "Scarcity that is true because it reads from contract state — not a manufactured countdown.",
    impact: "Engine",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-03",
    rank: 3,
    title: "Coordinator-first collateral",
    what: "Every venue asset written for the coordinator who forwards it, not the owner who signs it.",
    edge: "We design for the gatekeeper, not the buyer — the Sinéad test as the brief, not the review.",
    impact: "Engine",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-04",
    rank: 4,
    title: "Founder-signed letters, ≤50 a round",
    what: "A hand-written register, one wedge angle per round, no template smell.",
    edge: "A letter that names this venue's actual season, not 'Dear Partner'.",
    impact: "Engine",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-05",
    rank: 5,
    title: "Venue couple-handoff kit",
    what: "The venue-branded artifact every booked couple receives — the seeding mechanic, productised.",
    edge: "The venue stands behind the couple's planning: patronage, not software resale.",
    impact: "Engine",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "VE-06",
    rank: 6,
    title: "Patronage one-pager",
    what: "The pitch framed as the venue's gift to the couple, not a subscription upsell.",
    edge: "We sell the venue a way to be generous, not a tool to administer.",
    impact: "Engine",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-07",
    rank: 7,
    title: "Venue→venue warm referral chain",
    what: "Each signed venue introduces one peer; the founder facilitates, no cash incentive.",
    edge: "A referral that trades on taste reputation, not affiliate cash.",
    impact: "Engine",
    effort: "Low",
    month: "M4",
  },
  {
    id: "VE-08",
    rank: 8,
    title: "First-venue case study",
    what: "The proof artifact for the next forty-nine, told as one venue's planning season.",
    edge: "One named venue's real year, not a logo wall.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "VE-09",
    rank: 9,
    title: "Off-season pitch timing",
    what: "Approach venues Nov–Feb, when planning bandwidth is actually free.",
    edge: "We pitch when the coordinator can read, not when the season buries them.",
    impact: "High",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-10",
    rank: 10,
    title: "Regional cluster saturation",
    what: "Win one county's wedding scene first, for word-of-mouth density.",
    edge: "Depth in one room beats a thin presence in twenty.",
    impact: "High",
    effort: "Low",
    month: "M2–M4",
  },
  {
    id: "VE-11",
    rank: 11,
    title: "Taste-tier prospect research",
    what: "Rank Irish venues by design reputation; approach top-down, in that order.",
    edge: "We pursue the venues with taste, deliberately, on the record.",
    impact: "High",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-12",
    rank: 12,
    title: "Quiet-day restraint demo",
    what: "Show a venue Signal' 'nothing arrives' behaviour as proof of discipline.",
    edge: "The feature we demo is the email we choose not to send.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "VE-13",
    rank: 13,
    title: "Venue-edition anniversary artifact",
    what: "A year-in-review that makes renewal feel like keeping, not buying again.",
    edge: "Renewal as a ritual the venue would miss, not an invoice it questions.",
    impact: "High",
    effort: "Medium",
    month: "M5–M6",
  },
  {
    id: "VE-14",
    rank: 14,
    title: "The two-line venue email",
    what: "The entire pitch in two sentences a coordinator reads on a phone.",
    edge: "The brevity is itself the proof of the product.",
    impact: "High",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-15",
    rank: 15,
    title: "Reply-rate instrumented wedge test",
    what: "A/B the wedge angle across each ≤50 round; keep the angle that earns replies.",
    edge: "Only the angle that earns a reply survives into the next round.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "VE-16",
    rank: 16,
    title: "Founding-venue wall, earned not bought",
    what: "A restrained page naming the first venues, published only with their consent.",
    edge: "Names earn their place by signing; we never rent a logo.",
    impact: "High",
    effort: "Low",
    month: "M3",
  },
  {
    id: "VE-17",
    rank: 17,
    title: "The objection page",
    what: "Publish the honest answers to the three reasons a venue says no.",
    edge: "We publish our own objections before the venue has to raise them.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "VE-18",
    rank: 18,
    title: "Venue-readable pricing logic",
    what: "A page explaining why €1,500–4,000, in plain arithmetic.",
    edge: "We show the venue our maths, not a 'contact sales'.",
    impact: "High",
    effort: "Low",
    month: "M1",
  },
  {
    id: "VE-19",
    rank: 19,
    title: "The couple's first sixty seconds",
    what: "A demo of exactly what a sponsored couple sees on day one.",
    edge: "The venue buys what its couples will feel, shown — not described.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "VE-20",
    rank: 20,
    title: "Dormant-prospect re-touch",
    what: "One honest follow-up at the next season turn — never a chase sequence.",
    edge: "A single human follow-up, not an automated drip the coordinator can smell.",
    impact: "Medium",
    effort: "Low",
    month: "M4–M6",
  },
  {
    id: "VE-21",
    rank: 21,
    title: "Coordinator interview series",
    what: "Talk to five coordinators as private input; let it reshape the pitch.",
    edge: "The buyer rewrites our copy; we don't guess at it.",
    impact: "High",
    effort: "Low",
    month: "M1–M2",
  },
  {
    id: "VE-22",
    rank: 22,
    title: "One hand-delivered one-pager",
    what: "A single physical artifact to one flagship venue, founder-signed — no circuit.",
    edge: "One deliberate object for one venue, not a fair-booth handout.",
    impact: "Medium",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "VE-23",
    rank: 23,
    title: "The 'what we won't do to your couples' promise",
    what: "A written guarantee of no upsell, no spam, no data resale.",
    edge: "A vendor promising the venue what it will never do to their couples.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "VE-24",
    rank: 24,
    title: "Renewal-as-ritual script",
    what: "The M6 conversation designed so retention is the default and churn feels like loss.",
    edge: "We design the renewal moment, not just the sign-up moment.",
    impact: "Medium",
    effort: "Low",
    month: "M5–M6",
  },
];

const SPONSORED_LOOP: Approach[] = [
  {
    id: "SL-01",
    rank: 1,
    title: "'Planned in Signal · invited by [venue]' footer",
    what: "A restrained credit line on every shared Timeline and plan.",
    edge: "The attribution reads as a credit to the venue, not an ad for us.",
    impact: "Engine",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "SL-02",
    rank: 2,
    title: "Sponsored-couple → active onboarding",
    what: "A sequence engineered for the ≥40% sponsored-couple activation metric.",
    edge: "Built to the success metric, not to a generic welcome flow.",
    impact: "Engine",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SL-03",
    rank: 3,
    title: "Couple → wedding-party spillover",
    what: "Party members who see the workspace convert at the €79 Event tier.",
    edge: "The guest list is the funnel; the workspace is already in front of them.",
    impact: "High",
    effort: "Low",
    month: "M3",
  },
  {
    id: "SL-04",
    rank: 4,
    title: "Post-wedding keepsake plan",
    what: "The archived plan couples want to show their newly engaged friends.",
    edge: "We make the finished plan worth keeping, so it travels on its own.",
    impact: "High",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "SL-05",
    rank: 5,
    title: "Couple→couple referral at the finish line",
    what: "The moment they hand the venue back, they hand us forward.",
    edge: "The referral lives at the emotional peak, not behind a rewards tab.",
    impact: "High",
    effort: "Low",
    month: "M4",
  },
  {
    id: "SL-06",
    rank: 6,
    title: "Shareable milestone-countdown page",
    what: "A countdown page good enough to be posted without being asked.",
    edge: "The artifact earns the share by being worth looking at.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SL-07",
    rank: 7,
    title: "Timeline reply-by-email capture",
    what: "Turn a non-user reader's reply into a warm inbound conversation.",
    edge: "The reader who replies is already qualified; we just don't drop them.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "SL-08",
    rank: 8,
    title: "Vendor spillover hooks",
    what: "Photographers and florists in a couple's workspace adopt Tasks for their own jobs.",
    edge: "The vendor is in the workspace anyway; the second use case is free.",
    impact: "Medium",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "SL-09",
    rank: 9,
    title: "The guest-view that sells itself",
    what: "Design the surface a non-user sees first; that surface is the demo.",
    edge: "The product's pitch is the screen, not a separate landing page.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SL-10",
    rank: 10,
    title: "Opt-in anonymised plan gallery",
    what: "Real wedding plans, consented, as the only social proof we keep.",
    edge: "Proof that is real plans with permission, not invented screenshots.",
    impact: "Medium",
    effort: "Medium",
    month: "M5",
  },
  {
    id: "SL-11",
    rank: 11,
    title: "Workspace upgrade at the post-event high",
    what: "Event €79 → Workspace €120/yr offered at the emotional peak, once.",
    edge: "We ask once, at the moment it makes sense, then never again.",
    impact: "High",
    effort: "Low",
    month: "M5",
  },
  {
    id: "SL-12",
    rank: 12,
    title: "'Your year in Signal', restrained",
    what: "A tasteful recap that earns a forward — never Wrapped-loud.",
    edge: "A year-in-review that whispers; the restraint is the brand.",
    impact: "Medium",
    effort: "Medium",
    month: "M5",
  },
  {
    id: "SL-13",
    rank: 13,
    title: "Couple → trades/freelance crossover",
    what: "The same person, a second use case, with no new acquisition cost.",
    edge: "One acquired human, two jobs done — the suite earns the second.",
    impact: "Medium",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "SL-14",
    rank: 14,
    title: "The invite that explains nothing",
    what: "A shared link that needs no onboarding to understand, by design.",
    edge: "No onboarding step is the feature; the absence is the pitch.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "SL-15",
    rank: 15,
    title: "Activation-cohort proof, published at >40%",
    what: "The metric becomes the marketing the moment it is real.",
    edge: "We publish the number only after it's true, then let it speak.",
    impact: "Medium",
    effort: "Low",
    month: "M5",
  },
  {
    id: "SL-16",
    rank: 16,
    title: "Lapsed-couple reactivation at a friend's engagement",
    what: "A single, human, non-automated nudge when it's genuinely relevant.",
    edge: "One human message at a real moment, not a win-back campaign.",
    impact: "Medium",
    effort: "Low",
    month: "M5–M6",
  },
];

const SEARCH_COMPARISON: Approach[] = [
  {
    id: "SC-01",
    rank: 1,
    title: "'Why we don't have a dashboard'",
    what: "The flagship refusal as the anchor ranking essay.",
    edge: "The one page a generic competitor would never publish.",
    impact: "High",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "SC-02",
    rank: 2,
    title: "'Wedding planning spreadsheet alternative'",
    what: "Meet the actual current behaviour — the spreadsheet — honestly.",
    edge: "We name the tool they really use, instead of pretending it's a rival app.",
    impact: "High",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "SC-03",
    rank: 3,
    title: "Tasks vs Notion for wedding planning",
    what: "An honest comparison that names where Notion wins.",
    edge: "A comparison page that concedes the other tool's strengths.",
    impact: "High",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "SC-04",
    rank: 4,
    title: "'Software a contractor would actually open'",
    what: "The trades long-tail, in plain-English search intent.",
    edge: "We rank for how a builder talks, not how software markets itself.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-05",
    rank: 5,
    title: "Glossary-inversion page",
    what: "The PM words we refuse, and the plain words we use instead.",
    edge: "A comparison that compares vocabularies, not feature checkboxes.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-06",
    rank: 6,
    title: "'Monday.com is too much'",
    what: "The over-tooled-buyer angle, with no false claims.",
    edge: "We agree the buyer is over-served, then under-serve on purpose.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-07",
    rank: 7,
    title: "Own 'the plain-English project tool'",
    what: "The long-tail, non-jargon search intent nobody is targeting.",
    edge: "The phrase the 80% actually type, owned because nobody else wants it.",
    impact: "High",
    effort: "Medium",
    month: "M2–M4",
  },
  {
    id: "SC-08",
    rank: 8,
    title: "Trello alternative for people who don't think in cards",
    what: "A real cognitive angle, not a feature-for-feature table.",
    edge: "We name a way of thinking, not a missing card view.",
    impact: "Medium",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-09",
    rank: 9,
    title: "Asana for non-technical teams",
    what: "Honest about Asana's depth; clear about who we're for.",
    edge: "We tell the wrong-fit reader to stay on Asana.",
    impact: "Medium",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-10",
    rank: 10,
    title: "Reality-Anchor-audited comparisons",
    what: "Every claim links to shipped state; the page can't drift.",
    edge: "Comparison claims that cite our own changelog, not our marketing.",
    impact: "High",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "SC-11",
    rank: 11,
    title: "'The 80% not in tech' reference page",
    what: "The canonical explainer the industry can link to.",
    edge: "We define the audience so plainly the definition becomes the citation.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-12",
    rank: 12,
    title: "Wedding-coordinator workflow guide",
    what: "Genuinely useful, no signup, ranks, earns trust.",
    edge: "Useful enough to rank without asking for an email first.",
    impact: "High",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "SC-13",
    rank: 13,
    title: "Student-group project tool page",
    what: "The .edu-free hook, one honest landing page.",
    edge: "We give the tier away and say so plainly, no asterisk.",
    impact: "Medium",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "SC-14",
    rank: 14,
    title: "'What we don't collect' data page",
    what: "Restraint as a search-discoverable trust asset.",
    edge: "A page that ranks on the data we deliberately never store.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "SC-15",
    rank: 15,
    title: "Freelance 'tools too heavy' angle",
    what: "The pain stated plainly, the answer shown, not sold.",
    edge: "We state the freelancer's complaint in their words, then stop selling.",
    impact: "Medium",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "SC-16",
    rank: 16,
    title: "Internal-link spine across four products",
    what: "The suite reads as one — to readers and to search.",
    edge: "The four-product system is the SEO moat a single product can't build.",
    impact: "Medium",
    effort: "Medium",
    month: "M4",
  },
];

const PROOF_NARRATIVE: Approach[] = [
  {
    id: "PN-01",
    rank: 1,
    title: "The negative-CAC honesty essay",
    what: "'The venue giveaway produced nothing; a paid venue is the only honest channel.'",
    edge: "A founder publishing the line that flatters no one.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "PN-02",
    rank: 2,
    title: "One restrained founder video",
    what: "'Why I refuse the dashboard' — one asset, reused everywhere, not a series.",
    edge: "One video, made well; the refusal to make ten is the brand.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "PN-03",
    rank: 3,
    title: "The integrated four-product wedding demo",
    what: "Notes → Tasks → Timeline→ Signal, walked through one real wedding.",
    edge: "The system a single-product competitor structurally cannot show.",
    impact: "Engine",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "PN-04",
    rank: 4,
    title: "Dogfood: the company's own timeline is public",
    what: "Signal Studio's timeline is built and shared in Signal Timeline.",
    edge: "The proof is that we run the company on the product.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "PN-05",
    rank: 5,
    title: "Real-wedding dogfood account",
    what: "The founder plans an actual wedding on the suite, written up honestly.",
    edge: "Including what didn't work, because that's the part nobody else publishes.",
    impact: "High",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "PN-06",
    rank: 6,
    title: "The four-agent factory story",
    what: "How a solo studio ships without slop.",
    edge: "We show the assembly line, including the gate that rejects our own work.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "PN-07",
    rank: 7,
    title: "Changelog as marketing",
    what: "Per-product dispatches with genuine voice — already a strength.",
    edge: "A changelog written as sentences, not release-note bullets.",
    impact: "Medium",
    effort: "Low",
    month: "M1–M6",
  },
  {
    id: "PN-08",
    rank: 8,
    title: "One signature canonical essay",
    what: "The reference piece for 'tools for the 80% not in tech'.",
    edge: "One essay so clear it becomes the thing people link instead of arguing.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "PN-09",
    rank: 9,
    title: "The honest scorecard, mid-plan",
    what: "The five success metrics, scored in public, half-way through.",
    edge: "We publish the scoreboard whether or not we're winning.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "PN-10",
    rank: 10,
    title: "'What we refused this quarter'",
    what: "The moat made legible — once a quarter, never monthly.",
    edge: "A report whose entire content is the things we chose not to do.",
    impact: "Medium",
    effort: "Low",
    month: "M3–M6",
  },
  {
    id: "PN-11",
    rank: 11,
    title: "The first venue's own words",
    what: "A coordinator's account, named, not a testimonial blurb.",
    edge: "One real named person's sentences, not a five-star pull-quote.",
    impact: "High",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "PN-12",
    rank: 12,
    title: "The pricing-honesty essay",
    what: "Why annual prepay, why €79 one-time, what each tier is actually for.",
    edge: "We explain our pricing logic instead of obscuring it.",
    impact: "Medium",
    effort: "Low",
    month: "M2",
  },
  {
    id: "PN-13",
    rank: 13,
    title: "The arithmetic-before-marketing post",
    what: "The plan's own opening, made public.",
    edge: "We lead with the number that's under €75k without the venue.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "PN-14",
    rank: 14,
    title: "One well-made written AMA",
    what: "A single Q&A hosted on our own site, surfaced through communities.",
    edge: "Owned, edited, permanent — not an hour that scrolls away.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "PN-15",
    rank: 15,
    title: "Founder-signed everything",
    what: "Letters, essays, changelog all carry a name and accountability.",
    edge: "A name on every asset means someone can be wrong in public.",
    impact: "Medium",
    effort: "Low",
    month: "M1–M6",
  },
  {
    id: "PN-16",
    rank: 16,
    title: "The logo-swap test, on ourselves, in public",
    what: "We apply the gate to our own back-catalogue and publish the grades.",
    edge: "We fail our own assets in public before anyone else can.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
];

const BRAND_MOAT: Approach[] = [
  {
    id: "BM-01",
    rank: 1,
    title: "The banned-words manifesto page",
    what: "BRAND.md §3 published as a public standard.",
    edge: "A company publishing the words it refuses to sell with.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "BM-02",
    rank: 2,
    title: "The plain-English error library",
    what: "Every error message, public, as a credibility flex.",
    edge: "A discipline held in public is one a competitor cannot copy.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "BM-03",
    rank: 3,
    title: "'Everything important. Nothing distracting.' spine",
    what: "One line, held across all four products.",
    edge: "The same sentence everywhere is the proof of the discipline.",
    impact: "High",
    effort: "Low",
    month: "M1",
  },
  {
    id: "BM-04",
    rank: 4,
    title: "Silence-as-feature story",
    what: "Signal' quiet-day behaviour as the hero, not a footnote.",
    edge: "We market the email we choose not to send.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
  {
    id: "BM-05",
    rank: 5,
    title: "The one-pager set as collateral",
    what: "The PDFs as a downloadable, deliberate artifact system.",
    edge: "The collateral is restrained enough to be the product demo.",
    impact: "High",
    effort: "Low",
    month: "M1",
  },
  {
    id: "BM-06",
    rank: 6,
    title: "'Four products that read as one' diagram",
    what: "The suite-as-moat made legible in one image.",
    edge: "The system view a single-product competitor has nothing to draw.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "BM-07",
    rank: 7,
    title: "Anti-onboarding demo",
    what: "'No setup, no vocabulary to learn' — shown in twenty seconds.",
    edge: "The demo is over before a competitor's onboarding would begin.",
    impact: "High",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "BM-08",
    rank: 8,
    title: "The published exception log",
    what: "Zero brand-integrity exceptions, on the record.",
    edge: "A log whose value is that it stays empty.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "BM-09",
    rank: 9,
    title: "The kill-triggers, public",
    what: "What would make us change the plan, stated before it happens.",
    edge: "We publish the conditions under which we'd admit we were wrong.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "BM-10",
    rank: 10,
    title: "'Private by design' trust page",
    what: "Notes' privacy posture as a brand artifact.",
    edge: "Privacy stated as architecture, not a settings toggle.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "BM-11",
    rank: 11,
    title: "Claims-link-to-shipped discipline",
    what: "Every marketing claim hyperlinks to the commit or feature.",
    edge: "Marketing you can click through to the source code.",
    impact: "Medium",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "BM-12",
    rank: 12,
    title: "Named-only testimonial standard",
    what: "Only real, named, coordinator-forwarded quotes — quality over count.",
    edge: "We'd rather show one named quote than ten anonymous stars.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "BM-13",
    rank: 13,
    title: "The refusal as the about page",
    what: "The moat is the story; restraint, written plainly.",
    edge: "An about page that lists what we won't build.",
    impact: "Medium",
    effort: "Low",
    month: "M2",
  },
  {
    id: "BM-14",
    rank: 14,
    title: "One canonical 'what Signal Studio is' page",
    what: "The single URL the whole industry can be pointed to.",
    edge: "One page so clear it ends the 'so what is it' question.",
    impact: "High",
    effort: "Low",
    month: "M2",
  },
];

const COMMUNITY_PARTNERSHIPS: Approach[] = [
  {
    id: "CP-01",
    rank: 1,
    title: "Founder-signed answers in wedding-pro forums",
    what: "Value first, product second, never a drop-and-run.",
    edge: "We answer the question fully even when it doesn't mention us.",
    impact: "High",
    effort: "Low",
    month: "M2–M6",
  },
  {
    id: "CP-02",
    rank: 2,
    title: "Free no-signup wedding-planning checklist",
    what: "Genuinely useful, links back, no gate.",
    edge: "The useful thing is free with no email wall — that's the differentiator.",
    impact: "High",
    effort: "Medium",
    month: "M2",
  },
  {
    id: "CP-03",
    rank: 3,
    title: "Co-authored 'how we plan a wedding here now'",
    what: "A joint artifact with a flagship venue.",
    edge: "The venue co-signs the story, so it isn't ours alone.",
    impact: "High",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "CP-04",
    rank: 4,
    title: "Trades-community value posting",
    what: "The same plain-English wedge, in a different room.",
    edge: "We bring the contractor's own complaint, not a pitch.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "CP-05",
    rank: 5,
    title: "Freelance-community value posting",
    what: "Where 'tools too heavy' is the live complaint.",
    edge: "We agree the tools are too heavy and don't add one.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "CP-06",
    rank: 6,
    title: "One-campus student ambassador",
    what: "Organic, with the .edu-free tier as the hook.",
    edge: "One campus done properly, not a referral-code scheme.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "CP-07",
    rank: 7,
    title: "One wedding-industry podcast guest spot",
    what: "Restrained, founder, exactly one — not a circuit.",
    edge: "One conversation chosen for fit, not a booking spree.",
    impact: "Medium",
    effort: "Low",
    month: "M3",
  },
  {
    id: "CP-08",
    rank: 8,
    title: "Reciprocal essay swap with one indie founder",
    what: "Non-competing, audience-true, mutually useful.",
    edge: "One trade with someone whose audience is genuinely ours.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "CP-09",
    rank: 9,
    title: "'Tools the 80% actually use' linkable reference",
    what: "Honest enough that others cite it.",
    edge: "A reference that lists competitors fairly so it earns the link.",
    impact: "Medium",
    effort: "Medium",
    month: "M3",
  },
  {
    id: "CP-10",
    rank: 10,
    title: "Wedding-educator / course-supervisor relationship",
    what: "The Timeline persona, served directly.",
    edge: "We build for the supervisor who reads, not the team that writes.",
    impact: "Medium",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "CP-11",
    rank: 11,
    title: "One-time curated directory pass",
    what: "A single deliberate listing set — not the volume treadmill.",
    edge: "One considered pass, then we stop; the restraint is the point.",
    impact: "Medium",
    effort: "Low",
    month: "M2",
  },
  {
    id: "CP-12",
    rank: 12,
    title: "Vendor reciprocal mention",
    what: "Photographers and celebrants already in the workspace, credited mutually.",
    edge: "The credit is earned by working together, not paid for.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
  {
    id: "CP-13",
    rank: 13,
    title: "Irish small-business / craft cross-pollination",
    what: "The 80%-not-in-tech audience, met where they already are.",
    edge: "We go to the makers' rooms, not the software ones.",
    impact: "Medium",
    effort: "Medium",
    month: "M4",
  },
  {
    id: "CP-14",
    rank: 14,
    title: "One industry-publication opinion piece",
    what: "Data-free, conviction-rich, founder byline.",
    edge: "A position, argued, not a sponsored placement.",
    impact: "Medium",
    effort: "Low",
    month: "M4",
  },
];

export const MARKETING_BUCKETS: Bucket[] = [
  {
    key: "venue-engine",
    label: "venue engine",
    role: "The negative-CAC core — 75–85% of the six-month number.",
    rationale:
      "A paid venue is negative-CAC: it pays Signal Studio to seed fifty to a hundred and fifty high-intent couples into the suite every year, recurring. Without it the honest six-month number is under €75k. Every approach here moves the ≥10-paid-venues-by-M3 and ≥25%-close-rate metrics directly.",
    approaches: VENUE_ENGINE,
  },
  {
    key: "sponsored-loop",
    label: "sponsored loop",
    role: "Every shared artifact acquires — zero-marginal-cost compounding.",
    rationale:
      "The couples a venue sponsors are the distribution. Each shared plan is seen by the next engaged couple with venue trust attached. This bucket owns the ≥40% sponsored-couple → active-user metric and the M5–M6 self-sustaining-referral goal.",
    approaches: SPONSORED_LOOP,
  },
  {
    key: "search-comparison",
    label: "search & comparison",
    role: "The second leg — the hedge against 75% single-buyer concentration.",
    rationale:
      "The plan's named #1 kill-trigger is concentration on one buyer. Real-angle comparison and refusal-led search pages are the only structural hedge. No AI-listicle volume, no fabricated rivalries — every claim is reality-anchored to shipped state.",
    approaches: SEARCH_COMPARISON,
  },
  {
    key: "proof-narrative",
    label: "proof & narrative",
    role: "Founder voice — one of each, reused everywhere, never a treadmill.",
    rationale:
      "These are the conversion assets every channel points back to. One restrained video, one honest essay, one integrated demo. The honesty is the asset: a generic competitor will not publish the arithmetic that says the giveaway failed.",
    approaches: PROOF_NARRATIVE,
  },
  {
    key: "brand-moat",
    label: "brand as moat",
    role: "Productised refusal — the discipline made into distribution.",
    rationale:
      "Incumbents can copy a feature; they cannot copy a discipline held in public for two years. Publishing the refusals turns the moat into an acquisition surface that fails the logo-swap test by design.",
    approaches: BRAND_MOAT,
  },
  {
    key: "community-partnerships",
    label: "community & partnerships",
    role: "Value-first, non-paid — reach bought with usefulness, not spend.",
    rationale:
      "Every approach here is free and value-first by construction. No mass-blast, no paid placement, no daily posting quota. We earn the room by being useful in it, product second.",
    approaches: COMMUNITY_PARTNERSHIPS,
  },
];

export const MARKETING_TOTAL = MARKETING_BUCKETS.reduce(
  (n, b) => n + b.approaches.length,
  0,
);
